Sample code to support AppInsights quickstart
dotnet/samples pull request #4655
Opened 2021-06-15 23:49 UTC by CamSoper

[Related PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/162186)

I'm opting to put the sample here in the .NET samples repo because it's entirely possible we will continue to contribute changes to the Azure docs, and I really don't want to create a new repo in the Azure-Samples org for all of them.

2021-06-16 15:18 UTC, scottaddie requested changes

2021-06-16 15:18 UTC, scottaddie commented on azure/app-insights-aspnet-core-quickstart/README.md
> +dotnet run
Eliminate the build, since that will happen when running.

```suggestion
dotnet run
```

2021-06-16 15:18 UTC, scottaddie commented on azure/app-insights-aspnet-core-quickstart/README.md
> +Add replace the placeholder InstumentationKey in *appsettings.json* with your actual InstumentationKey.
```suggestion
Replace the placeholder `ApplicationInsights:InstrumentationKey` value in *appsettings.json* with your actual instrumentation key.
```

2021-06-16 15:18 UTC, scottaddie commented on azure/app-insights-aspnet-core-quickstart/README.md
> +* A configuration value for `ApplicationInsights.InstrumentationKey` was added to *appsettings.json*.
```suggestion
* A configuration value for `ApplicationInsights:InstrumentationKey` was added to *appsettings.json*.
```

2021-06-16 15:18 UTC, scottaddie commented on azure/app-insights-aspnet-core-quickstart/README.md
> +As you use the app, telemetry will be ingested to Application Insights within a few minutes. You can verify the connection using Live metrics.
```suggestion
As you use the app, telemetry will be ingested to Application Insights within a few minutes. You can verify the connection using Live Metrics.
```

2021-06-16 17:51 UTC, IEvangelist approved these changes
The only thing I'm curious about is whether or not the _/dist_ folder should be source controlled?

2021-06-16 19:40 UTC, merged

2021-06-16 22:05 UTC, scottaddie commented
@IEvangelist This is a rare case in which *dist* should be source-controlled. The directory is part of the [Razor Pages project template](https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/wwwroot/lib/jquery).

2021-06-17 13:00 UTC, IEvangelist commented
> @IEvangelist David Pine FTE This is a rare case in which _dist_ should be source-controlled. The directory is part of the [Razor Pages project template](https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/wwwroot/lib/jquery).

Yes, I realized that after the fact - and discussed it with Cam directly.