Update pattern matching tutorial to .NET 6
dotnet/samples pull request #5090
Opened 2022-04-08 15:31 UTC by stvansolano

## Summary

Contributes to #4953 For 'Pattern matching tutorial' + some C# 9 tweaks

Also keep the files consistent with the tutorial samples from [docs/csharp/fundamentals/tutorials/pattern-matching.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/pattern-matching.md) aka live -> https://docs.microsoft.com/dotnet/csharp/fundamentals/tutorials/pattern-matching

cc @adegeo @BillWagner @IEvangelist

2022-04-11 17:15 UTC, BillWagner requested changes
This is great work @stvansolano Thank you!

I noticed one mistake that needs to be addressed before we merge this.

2022-04-11 17:15 UTC, BillWagner commented on csharp/tutorials/patterns/start/toll-calculator/Program.cs
> +using toll_calculator;
This looks like a copy / paste error:

```suggestion
namespace toll_calculator;
```

2022-04-13 14:10 UTC, stvansolano commented
Thanks @BillWagner looks good to me. Feel free to commit any other change you consider appropriate.

2022-04-13 15:07 UTC, stvansolano commented
@BillWagner I added a new change in order to prevent build errors on `/start` Program.cs file given that was supposed to be empty. So keeping some lines on code out of comments makes the build and top-level program happy.

2022-04-13 15:12 UTC, BillWagner approved these changes

2022-04-13 15:12 UTC, BillWagner commented
Thanks for fixing the build issues @stvansolano 

I'll :shipit: now.

2022-04-13 15:12 UTC, merged