Revamp Orleans shopping cart example | .NET 8 + Azure Cosmos DB for NoSQL
dotnet/samples pull request #6213
Opened 2023-10-04 17:21 UTC by seesharprun

Changes:
- [x] Change package versions from static to floating (ex. `7.x`)
- [x] Pushed forward to .NET 8
- [x] Ran `dotnet format`
- [x]

2023-10-05 17:44 UTC, seesharprun commented
@IEvangelist and @bradygaster, this sample will be ready for review next week after I add the Dockerfile

2023-10-18 17:58 UTC, IEvangelist requested changes

2023-10-18 17:58 UTC, IEvangelist commented on orleans/ShoppingCart/Grains/Orleans.ShoppingCart.Grains.csproj
> +    <PackageReference Include="Microsoft.Orleans.Sdk" Version="7.*" />
```suggestion
    <PackageReference Include="Microsoft.Orleans.Runtime" Version="8.*" />
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="8.*" />
```

2023-10-18 17:58 UTC, IEvangelist commented on orleans/ShoppingCart/Abstractions/Orleans.ShoppingCart.Abstractions.csproj
> +    <PackageReference Include="Microsoft.Orleans.Sdk" Version="7.*" />
Hold for Orleans 8.0.0-rc.2

```suggestion
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="8.*" />
```

2023-10-18 18:07 UTC, seesharprun commented
@IEvangelist, How do you feel about a [floating version resolution](https://learn.microsoft.com/nuget/concepts/package-versioning#floating-version-resolutions)?

```xml
<PackageReference Include="Microsoft.Orleans.Server" Version="8.*-*" />
```

That syntax should cover both pre-release and release variants of 8.x

I use this technique for [`Azure.AI.OpenAI`](https://www.nuget.org/packages/Azure.AI.OpenAI) over in our Cosmos+OpenAI training module: 

- https://github.com/Azure-Samples/cosmosdb-chatgpt/blob/main/cosmoschatgpt.csproj#L13

2024-01-05 20:48 UTC, IEvangelist approved these changes

2024-01-05 20:48 UTC, merged